// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.2
// 	protoc        v5.29.3
// source: proto/authentication/protos/authentication.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignInMethod int32

const (
	SignInMethod_PASSWORD SignInMethod = 0
	SignInMethod_OTP      SignInMethod = 1
)

// Enum value maps for SignInMethod.
var (
	SignInMethod_name = map[int32]string{
		0: "PASSWORD",
		1: "OTP",
	}
	SignInMethod_value = map[string]int32{
		"PASSWORD": 0,
		"OTP":      1,
	}
)

func (x SignInMethod) Enum() *SignInMethod {
	p := new(SignInMethod)
	*p = x
	return p
}

func (x SignInMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignInMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_authentication_protos_authentication_proto_enumTypes[0].Descriptor()
}

func (SignInMethod) Type() protoreflect.EnumType {
	return &file_proto_authentication_protos_authentication_proto_enumTypes[0]
}

func (x SignInMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignInMethod.Descriptor instead.
func (SignInMethod) EnumDescriptor() ([]byte, []int) {
	return file_proto_authentication_protos_authentication_proto_rawDescGZIP(), []int{0}
}

type SigninRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumber   string                 `protobuf:"bytes,1,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	SignInMethod  SignInMethod           `protobuf:"varint,4,opt,name=signInMethod,proto3,enum=authentication.SignInMethod" json:"signInMethod,omitempty"`
	Password      *string                `protobuf:"bytes,2,opt,name=password,proto3,oneof" json:"password,omitempty"`
	Otp           *string                `protobuf:"bytes,3,opt,name=otp,proto3,oneof" json:"otp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SigninRequest) Reset() {
	*x = SigninRequest{}
	mi := &file_proto_authentication_protos_authentication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigninRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigninRequest) ProtoMessage() {}

func (x *SigninRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authentication_protos_authentication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigninRequest.ProtoReflect.Descriptor instead.
func (*SigninRequest) Descriptor() ([]byte, []int) {
	return file_proto_authentication_protos_authentication_proto_rawDescGZIP(), []int{0}
}

func (x *SigninRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *SigninRequest) GetSignInMethod() SignInMethod {
	if x != nil {
		return x.SignInMethod
	}
	return SignInMethod_PASSWORD
}

func (x *SigninRequest) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *SigninRequest) GetOtp() string {
	if x != nil && x.Otp != nil {
		return *x.Otp
	}
	return ""
}

type SigninResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *Token                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SigninResponse) Reset() {
	*x = SigninResponse{}
	mi := &file_proto_authentication_protos_authentication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigninResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigninResponse) ProtoMessage() {}

func (x *SigninResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authentication_protos_authentication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigninResponse.ProtoReflect.Descriptor instead.
func (*SigninResponse) Descriptor() ([]byte, []int) {
	return file_proto_authentication_protos_authentication_proto_rawDescGZIP(), []int{1}
}

func (x *SigninResponse) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

var File_proto_authentication_protos_authentication_proto protoreflect.FileDescriptor

var file_proto_authentication_protos_authentication_proto_rawDesc = []byte{
	0x0a, 0x30, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x61, 0x75,
	0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0e, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x1a, 0x28, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e,
	0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc0, 0x01, 0x0a,
	0x0d, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20,
	0x0a, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x12, 0x40, 0x0a, 0x0c, 0x73, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x4d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x52, 0x0c, 0x73, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x4d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x12, 0x1f, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x88, 0x01, 0x01, 0x12, 0x15, 0x0a, 0x03, 0x6f, 0x74, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x01, 0x52, 0x03, 0x6f, 0x74, 0x70, 0x88, 0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x6f, 0x74, 0x70, 0x22,
	0x3d, 0x0a, 0x0e, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2b, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2a, 0x25,
	0x0a, 0x0c, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x0c,
	0x0a, 0x08, 0x50, 0x41, 0x53, 0x53, 0x57, 0x4f, 0x52, 0x44, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03,
	0x4f, 0x54, 0x50, 0x10, 0x01, 0x32, 0x60, 0x0a, 0x15, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x47,
	0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x12, 0x1d, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x65,
	0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e,
	0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_authentication_protos_authentication_proto_rawDescOnce sync.Once
	file_proto_authentication_protos_authentication_proto_rawDescData = file_proto_authentication_protos_authentication_proto_rawDesc
)

func file_proto_authentication_protos_authentication_proto_rawDescGZIP() []byte {
	file_proto_authentication_protos_authentication_proto_rawDescOnce.Do(func() {
		file_proto_authentication_protos_authentication_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_authentication_protos_authentication_proto_rawDescData)
	})
	return file_proto_authentication_protos_authentication_proto_rawDescData
}

var file_proto_authentication_protos_authentication_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_authentication_protos_authentication_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_authentication_protos_authentication_proto_goTypes = []any{
	(SignInMethod)(0),      // 0: authentication.SignInMethod
	(*SigninRequest)(nil),  // 1: authentication.SigninRequest
	(*SigninResponse)(nil), // 2: authentication.SigninResponse
	(*Token)(nil),          // 3: authentication.Token
}
var file_proto_authentication_protos_authentication_proto_depIdxs = []int32{
	0, // 0: authentication.SigninRequest.signInMethod:type_name -> authentication.SignInMethod
	3, // 1: authentication.SigninResponse.token:type_name -> authentication.Token
	1, // 2: authentication.AuthenticationService.SignIn:input_type -> authentication.SigninRequest
	2, // 3: authentication.AuthenticationService.SignIn:output_type -> authentication.SigninResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_authentication_protos_authentication_proto_init() }
func file_proto_authentication_protos_authentication_proto_init() {
	if File_proto_authentication_protos_authentication_proto != nil {
		return
	}
	file_proto_authentication_protos_common_proto_init()
	file_proto_authentication_protos_authentication_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_authentication_protos_authentication_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_authentication_protos_authentication_proto_goTypes,
		DependencyIndexes: file_proto_authentication_protos_authentication_proto_depIdxs,
		EnumInfos:         file_proto_authentication_protos_authentication_proto_enumTypes,
		MessageInfos:      file_proto_authentication_protos_authentication_proto_msgTypes,
	}.Build()
	File_proto_authentication_protos_authentication_proto = out.File
	file_proto_authentication_protos_authentication_proto_rawDesc = nil
	file_proto_authentication_protos_authentication_proto_goTypes = nil
	file_proto_authentication_protos_authentication_proto_depIdxs = nil
}
