syntax = "proto3";

package authentication;

option go_package = "./";


import "gw/user_gw_grpc/proto/authentication/protos/common.proto";

service AuthenticationService {

  rpc SignUp (SignUpRequest) returns (Empty);
  rpc SignIn (SignInRequest) returns (SignInResponse);
  rpc Verify (VerifyRequest) returns (Token);
  rpc ResetPassword (ResetPasswordRequest) returns (Empty);
  rpc ChangePassword (ChangePasswordRequest) returns (Empty);
  rpc RefreshToken (Token) returns (Token);
}



message SignUpRequest{
  string phoneNumber = 1;
  string password =2;
}

message SignInRequest{
  string phoneNumber =1;
  SignInMethod signInMethod =2;
  optional string password=3;
}
message SignInResponse{
  optional Token token=1;
}

enum SignInMethod{
  PASSWORD = 0;
  VERIFY_CODE = 1;
}

enum VerifyMethod{
  SIGNUP = 0;
  SIGNIN = 1;
}

message VerifyRequest{
  VerifyMethod verifyMethod=1;
  VerifyCode verifyCode=2;
}

message ResetPasswordRequest{
  string phoneNumber =1;
}

message ChangePasswordRequest{
  VerifyCode code =1;
  string password =2;
}
